---
title: "2020_reg"
output: html_notebook
---

I decide to focus on 2020 (Ottobre 2019 a Ottobre 2020), as suggested from exploratory analysis:

```{r}
library(ggmap)
data <- read.csv("../../data/new_data/data_bystate_temp_perc.csv")
state_coords <- read.csv("../../data/state_coords_lon_lat.csv")

data2020 <- data[(data$year==2019 & data$months=="Q4")|(data$year==2020 & 
                                                          ((data$months=="Q1")|(data$months=="Q2")|(data$months=="Q3"))),]


season <- ifelse((data2020$months == "Q1" | data2020$months == "Q4"),"winter","summer")
data2020 <- cbind(data2020, season)



head(data2020)
```
```{r}
with(data2020, plot(x=colony_added, y=colony_lost, log="xy"))
```


Let's try to fit the regression:
```{r}
model_gam = gam(colony_lost ~ colony_n + season + colony_added + s(Varroa.mites, bs='cr')
                + s(Other.pests.parasites, bs='cr') + s(Disesases, bs='cr')
                + s(Pesticides, bs='cr') + s(Other, bs='cr') + s(Unknown, bs='cr')
                + s(MaximumTemperature, bs='cr') + MinimumTemperature, data=data2020)
summary(model_gam) #-> edf : grado di non-linearita

```

```{r}
plot(model_gam)
```




