---
title: "survival"
output: html_document
date: "2022-12-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
```

```{r import data}
data<-read.csv("survival.csv")
```

```{r plot, echo=FALSE}
ggplot(data=data,aes(x=state,y=time)) + 
  geom_bar(stat='identity',width=0.2) +
  geom_point(aes(color=status,shape=status),size=2) +
  coord_flip()

```

```{r}
#response variable (time to event and status for death)
y<-Surv(data$time, data$status=="Event")
#survival curve --> KM estimator
fit <- survfit(y ~ 1, data = data)
ggsurvplot(fit,
           data=data,
           risk.table = TRUE, # Add risk table
           risk.table.col = "strata", # Change risk table color by groups
           surv.median.line = "hv", # Specify median survival
           ggtheme = theme_bw(), # Change ggplot2 theme
           #break.time.by=90,
           title="Kaplan-Meier Curve for Lung Cancer Survival")
```

```{r}
cumulative_incidence <- 1 - fit$surv
ggsurvplot(fit,
           data=data,
           risk.table = TRUE, # Add risk table
           risk.table.col = "strata", # Change risk table color by groups
           surv.median.line = "hv", # Specify median survival
           ggtheme = theme_bw(), # Change ggplot2 theme
           #break.time.by=90,
           fun='event',
           title="Cumulative Incidence Curve for Lung Cancer Survival")
```

```{r}
#MINIMUM TEMPERATURE
groups <- levels(factor(data$state))
df <- data.frame(
  state = tolower(groups),
  values = data$clusterMIN
)
library(usmap)
plot_usmap(data = df) + labs(title = "Cluster by avg temp")
                  +colors=c("forestgreen","firebrick1","dodgerblue2")

```

```{r}
fit.MIN <- survfit(Surv(time, status=="Event") ~ clusterMIN, data=data)
ggsurvplot(fit.MIN, 
           data=data,
           conf.int = F,
           risk.table = TRUE, # Add risk table
           risk.table.col = "strata", # Change risk table color by groups
           surv.median.line = "hv", # Specify median survival
           ggtheme = theme_bw(), # Change ggplot2 theme
           legend.labs=c("northern states","southern  states","central states"),   
           palette=c("forestgreen","firebrick1","dodgerblue2"), 
           title="Kaplan-Meier Curves by cluster for temp min")

#It looks like there’s some differences in the curves 
#Is there statistical evidence for that difference?
log_rank_test <- survdiff(Surv(time, status=="Event") ~ clusterMIN, data=data)
hazard_ratio <- (log_rank_test$obs[1]/log_rank_test$exp[1])/(log_rank_test$obs[2]/log_rank_test$exp[2])
hazard_ratio
#temp min
#HR= zard_ratio=0.4538251

```

the risk of death in the northen staes (harsh winters) is 0.45 times the risk in the southern staes (warmer winters)

```{r}
#PRECIPITATION
groups <- levels(factor(data$state))
df <- data.frame(
  state = tolower(groups),
  values = data$clusterPREC
)
library(usmap)
plot_usmap(data = df) + labs(title = "Cluster by prec")

fit.PREC <- survfit(Surv(time, status=="Event") ~ clusterPREC, data=data)
ggsurvplot(fit.PREC, 
           data=data,
           conf.int = F,
           risk.table = TRUE, # Add risk table
           #risk.table.col = "strata", # Change risk table color by groups
           surv.median.line = "hv", # Specify median survival
           ggtheme = theme_bw(), # Change ggplot2 theme
           legend.labs=c("cluster3","cluster1","cluster2"),   
           palette=c("dodgerblue2","firebrick1","forestgreen"), 
           title="Kaplan-Meier Curves by cluster for PREC")

#It looks like there’s some differences in the curves 
#Is there statistical evidence for that difference?
log_rank_test <- survdiff(Surv(time, status=="Event") ~ clusterPREC, data=data)
hazard_ratio <- (log_rank_test$obs[2]/log_rank_test$exp[2])/(log_rank_test$obs[1]/log_rank_test$exp[1])
hazard_ratio
```

HR= zard_ratio=0.4250286 the risk of deaths in cluster1 (states where the preciptation are higher) is 0.4250286 times the risk in cluster2 (states where the preciptation are much lower)

```{r}
###MODEL
cox.age <- coxph(Surv(time, status=="Event") ~ AverageTemperature+Precipitation+PalmerDroughtSeverityIndexPDSI+clusterMIN, data = data)
summary(cox.age)
#holding the other covariates constant:
#the higher the temperature the lower the death (0.76265)
#higer temperature is associated with good prognostic.
#the higher the precipitation the lower the death (0.59427)
#higer precipitation is associated with good prognostic.
#the higher the PDSI (dry condition)index the higher the risk of death (1.24040)
#dry condition is associated with bad prognostic.
#as seen before states belonging to cluster2 have a lower probability of dying w.r.t state in cluster 1 

#The p-values for all three overall tests (likelihood, Wald, and score) are extremely small, 
#indicating that the model is significant
ggforest(cox.age, data=data)
#Goodness of fit
ggcoxdiagnostics(cox.age, type = "martingale")
#the residual are centered around 0 and not oscillating above or below 0!

```
