---
title: "Ambiental cluster"
output: html_notebook
---



```{r}
head(readstate)
multi_cluster <- readstate %>%
  group_by(state,months) %>%
  summarise(MaximumTemperature= max(MaximumTemperature),
            MinimumTemperature= min(MinimumTemperature),
            Precipitation = mean(Precipitation), 
            AverageTemperature = mean(AverageTemperature),
            PalmerDroughtSeverityIndexPDSI = mean(PalmerDroughtSeverityIndexPDSI)
            )

multi_cluster <- multi_cluster %>%
  group_by(state) %>%
  summarise(max(MaximumTemperature), min(MinimumTemperature), mean(Precipitation)
            , mean(AverageTemperature), mean(PalmerDroughtSeverityIndexPDSI))


multi_cluster[multi_cluster$state=="Alaska",6] <- 0
which(is.na(multi_cluster))
```
```{r}
  dataset.e <- dist(multi_cluster, method = 'euclidean') #no method -> euclidean (default)

  dataset.es <- hclust(dataset.e, method = 'single') 
  dataset.ea <- hclust(dataset.e, method = 'average')
  dataset.ec <- hclust(dataset.e, method = 'complete')
  dataset.ew <- hclust(dataset.e, method = 'ward.D2')
  
  #plot of dendograms
  par(mfrow=c(1,3))
  plot(dataset.es, main='euclidean-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ec, main='euclidean-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ea, main='euclidean-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ew, main='euclidean-ward', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

  
  #cutting dendograms: (with k=2 fixed)
  cluster.ec <- cutree(dataset.ec, k=3) # euclidean-complete:
  cluster.ea <- cutree(dataset.ea, k=3) # euclidean-average:
  cluster.es <- cutree(dataset.es, k=3) # euclidean-simple:
  cluster.ew <- cutree(dataset.ew, k=3) # euclidean-simple:

  
  
  # Let's give a mark to the algorithms: did they aggregate coherently with
  # the dissimilarity matrix or not?
  # compute the cophenetic matrices 
  coph.es <- cophenetic(dataset.es)
  coph.ec <- cophenetic(dataset.ec)
  coph.ea <- cophenetic(dataset.ea)
  coph.ew <- cophenetic(dataset.ew)

  
  # compute cophenetic coefficients (<-> corr(D,C)) D:dist mat; C:coph dist mat
  es <- cor(dataset.e, coph.es)
  ec <- cor(dataset.e, coph.ec)
  ea <- cor(dataset.e, coph.ea)
  ew <- cor(dataset.e, coph.ew)

  
  c("Eucl-Single"=es,"Eucl-Compl."=ec,"Eucl-Ave."=ea, "Eucl-War."=ew)

```
Ha più senso utilizzare Euclidean-Average con k=3

```{r}
library(plotly)
us_data <- map_data("state")
df <- data.frame(
  state = tolower(multi_cluster$state),
  values = cluster.ew
)

library(usmap)
plot_usmap(data = df) + labs(title = "Multivariate cluster (all cov)")

```

#Now standardize data
```{r}
std_multi_cluster<- scale(multi_cluster[,-1])
dataset.e <- dist(std_multi_cluster, method = 'euclidean') #no method -> euclidean (default)

  dataset.es <- hclust(dataset.e, method = 'single') 
  dataset.ea <- hclust(dataset.e, method = 'average')
  dataset.ec <- hclust(dataset.e, method = 'complete')
  dataset.ew <- hclust(dataset.e, method = 'ward.D2')
  
  #plot of dendograms
  par(mfrow=c(1,3))
  plot(dataset.es, main='euclidean-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ec, main='euclidean-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ea, main='euclidean-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ew, main='euclidean-ward', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

  
  #cutting dendograms: (with k=2 fixed)
  cluster.ec <- cutree(dataset.ec, k=3) 
  cluster.ea <- cutree(dataset.ea, k=4) # va bene 3 o 4
  cluster.es <- cutree(dataset.es, k=3) 
  cluster.ew <- cutree(dataset.ew, k=4) #va bene 3 o 4

  
  
  # Let's give a mark to the algorithms: did they aggregate coherently with
  # the dissimilarity matrix or not?
  # compute the cophenetic matrices 
  coph.es <- cophenetic(dataset.es)
  coph.ec <- cophenetic(dataset.ec)
  coph.ea <- cophenetic(dataset.ea)
  coph.ew <- cophenetic(dataset.ew)

  
  # compute cophenetic coefficients (<-> corr(D,C)) D:dist mat; C:coph dist mat
  es <- cor(dataset.e, coph.es)
  ec <- cor(dataset.e, coph.ec)
  ea <- cor(dataset.e, coph.ea)
  ew <- cor(dataset.e, coph.ew)

  
  c("Eucl-Single"=es,"Eucl-Compl."=ec,"Eucl-Ave."=ea, "Eucl-War."=ew)
```
Anche in questo caso E-A ma k=2 migliore (ignoreremo ciò e usiamo k=3)
```{r}
library(plotly)
us_data <- map_data("state")
df <- data.frame(
  state = tolower(multi_cluster$state),
  values = cluster.ew
)

library(usmap)
plot_usmap(data = df) + labs(title = "Std Multivariate cluster (all cov)")
```

## CLUSTER SENZA PDSI
```{r}
std_multi_cluster<- scale(multi_cluster[,-c(1,6)])
dataset.e <- dist(std_multi_cluster, method = 'euclidean') #no method -> euclidean (default)

  dataset.es <- hclust(dataset.e, method = 'single') 
  dataset.ea <- hclust(dataset.e, method = 'average')
  dataset.ec <- hclust(dataset.e, method = 'complete')
  dataset.ew <- hclust(dataset.e, method = 'ward.D2')
  
  #plot of dendograms
  par(mfrow=c(1,3))
  plot(dataset.es, main='euclidean-single', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ec, main='euclidean-complete', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ea, main='euclidean-average', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')
  plot(dataset.ew, main='euclidean-ward', hang=-0.1, xlab='', labels=F, cex=0.6, sub='')

  
  #cutting dendograms: (with k=2 fixed)
  cluster.ec <- cutree(dataset.ec, k=3) # euclidean-complete:
  cluster.ea <- cutree(dataset.ea, k=3) # euclidean-average:
  cluster.es <- cutree(dataset.es, k=3) # euclidean-simple:
  cluster.ew <- cutree(dataset.ew, k=4) # euclidean-simple:

  
  
  # Let's give a mark to the algorithms: did they aggregate coherently with
  # the dissimilarity matrix or not?
  # compute the cophenetic matrices 
  coph.es <- cophenetic(dataset.es)
  coph.ec <- cophenetic(dataset.ec)
  coph.ea <- cophenetic(dataset.ea)
  coph.ew <- cophenetic(dataset.ew)

  
  # compute cophenetic coefficients (<-> corr(D,C)) D:dist mat; C:coph dist mat
  es <- cor(dataset.e, coph.es)
  ec <- cor(dataset.e, coph.ec)
  ea <- cor(dataset.e, coph.ea)
  ew <- cor(dataset.e, coph.ew)

  
  c("Eucl-Single"=es,"Eucl-Compl."=ec,"Eucl-Ave."=ea, "Eucl-War."=ew)
```
```{r}
library(plotly)
us_data <- map_data("state")
df <- data.frame(
  state = tolower(multi_cluster$state),
  values = cluster.ew
)

library(usmap)
plot_usmap(data = df) + labs(title = "Std Multivariate cluster (without PDSI)")
```

```{r}
plot_ly(x=std_multi_cluster[,1], y=std_multi_cluster[,2], z=std_multi_cluster[,3], color=cluster.ew, pch=19)
```

