---
title: "R Notebook"
output: html_notebook
---

```{r}
load("cleaned_data.Rda")
colony <- read_csv("data/colony.csv")

d <- read.csv('data_merged.csv')
d[is.na(d)] <- 0

states.name <- factor(d$state)
i1<-which(states.name==c("United States"))
d<-d[-i1,]

i2<-which(d$months=="April-June"&d$year=="2019")
d<-d[-i2,]
```

## SEASON

```{r}
## aggregate data by season
seasonal <- d %>% mutate(
  period = case_when(
  months=='January-March' ~ paste('winter',year,sep='-'),
  months=='October-December' ~ paste('winter',year+1,sep='-'),
  months=='April-June' ~ paste('summer',year,sep='-'),
  months=='July-September' ~ paste('summer',year,sep='-')
))
```

## CLUSTERS

```{r canberra-complete 3 clusters}
library(plotly)
us_data <- map_data("state")

df <- data.frame(
  state = tolower(X$state),
  values = as.numeric(group)
)

library(usmap)
plot_usmap(data = df) + labs(title = "Colony lost percentage in 2020") + scale_fill_gradientn(colors = c("#1b98e0", "#f6f805", "#353436"))
#nota che gli stati vuoti sarebbero in Others
```

```{r, canberra-complete 4 clusters}
us_data <- map_data("state")

df <- data.frame(
  state = tolower(X_prova$state),
  values = as.numeric(group)
)

plot_usmap(data = df) + labs(title = "Colony lost percentage in 2020")+ scale_fill_gradientn(colors = c("#1b98e0", "#f6f805", "#353436"))
```

```{r k-means 3 clusters}
us_data <- map_data("state")

df <- data.frame(
  state = tolower(X_prova$state),
  values = as.numeric(group)
)

plot_usmap(data = df) + labs(title = "Colony lost percentage in 2020")+ scale_fill_gradientn(colors = c("#1b98e0", "#f6f805", "#353436"))
```
