---
title: "Regression"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/lucamainini/Documents/GitHub/np_project/")
```

```{r import data}
library(readr)
data_bystate_temp_perc <- read_csv("data/new_data/data_bystate_temp_perc.csv")
```

```{r}
library(dplyr)
data <- data_bystate_temp_perc %>% mutate(colony_lost_pct = colony_lost_pct/100)
data <- data %>% mutate(Varroa.mites = Varroa.mites/100)
data <- data %>% mutate(Other.pests.parasites = Other.pests.parasites/100)
data <- data %>% mutate(Disesases = Disesases/100)
data <- data %>% mutate(Pesticides = Pesticides/100)
data <- data %>% mutate(Other = Other/100)
data <- data %>% mutate(Unknown = Unknown/100)
```

## LINEAR MODEL

```{r}
lin_mod_n <- lm(data=data, colony_lost ~ colony_max + state + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown+year)
summary(lin_mod_n)
```

```{r}
lin_mod <- lm(data=data, colony_lost_pct ~ state + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown)
summary(lin_mod)
```

```{r}
library(car)
b <- coefficients(lin_mod)
e <- residuals(lin_mod)

cat("Verify the hypothesis:\n")
par(mfrow=c(2,2))
plot(lin_mod)


par(mfrow=c(1,1))
cat("Verify normality of residuals:\n")
shapiro.test(residuals(lin_mod))
shapiro.test(rstudent(lin_mod))

cat("VIF:\n")
vif(lin_mod)
```

Le ipotesi del modello lineare non sono verificate.

## LOGIT

Non so se logit va bene visto che abbiamo valori nell'intervallo 0-1 e non 0,1.

```{r}
data = data %>% mutate(logit_colony_lost_pct=logit(colony_lost_pct))
```

```{r}
logit_mod <- lm(data=data, logit_colony_lost_pct ~ state + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown)
summary(logit_mod)

AIC(logit_mod)

cat("Verify the hypothesis:\n")
par(mfrow=c(2,2))
plot(logit_mod)


par(mfrow=c(1,1))
cat("Verify normality of residuals:\n")
shapiro.test(residuals(logit_mod))
shapiro.test(rstudent(logit_mod))

cat("VIF:\n")
vif(logit_mod)
```

```{r}
library(outliers)
x = outlierTest(logit_mod)
x
```

```{r}
data_without_outliers = data[-c(897,921),]

logit_mod <- lm(data=data_without_outliers, logit_colony_lost_pct ~ state + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown)
summary(logit_mod)

AIC(logit_mod)

cat("Verify the hypothesis:\n")
par(mfrow=c(2,2))
plot(logit_mod)


par(mfrow=c(1,1))
cat("Verify normality of residuals:\n")
shapiro.test(residuals(logit_mod))
shapiro.test(rstudent(logit_mod))

cat("VIF:\n")
vif(logit_mod)
```

```{r}
# GLM NON DA USARE
logit_mod <- glm(colony_lost_pct ~ months + state + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown,
                  data = data,family = "binomial")
summary(logit_mod)

AIC(logit_mod)

cat("Verify the hypothesis:\n")
par(mfrow=c(2,2))
plot(logit_mod)


par(mfrow=c(1,1))
cat("Verify normality of residuals:\n")
shapiro.test(residuals(logit_mod))
shapiro.test(rstudent(logit_mod))

cat("VIF:\n")
vif(logit_mod)
```

# BETA REGRESSION

```{r}
require(betareg)
beta_mod <- betareg(colony_lost_pct ~ months + Varroa.mites + Other.pests.parasites+Disesases+Pesticides+Other+Unknown + state,
                  data = data)
summary(beta_mod)
AIC(beta_mod)
```

# Linear Mixed Models

```{r}
library(lme4)
lm_mod <- lmer(colony_lost_pct ~ year + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown + (1|state),
                  data = data)
summary(lm_mod)
AIC(lm_mod)
```

```{r}
fm16.1mer = lm_mod
plot(fm16.1mer)
shapiro.test(residuals(fm16.1mer))
```

```{r}
library(lme4)
library(insight)
confint(fm16.1mer,oldNames=TRUE)

## Var-Cov matrix of fixed-effects
vcovb <- vcov(fm16.1mer) 
cat("\nVar-Cov matrix of fixed-effects:\n")
vcovb
corb <- cov2cor(vcovb) 
nms <- abbreviate(names(fixef(fm16.1mer)), 5)
rownames(corb) <- nms
cat("\nCorrelation matrix of fixed-effects:\n")
corb

cat("Var-Cov matrix of random-effects and errors\n")
print(vc <- VarCorr(fm16.1mer), comp = c("Variance", "Std.Dev."))

sigma2_eps <- as.numeric(get_variance_residual(fm16.1mer))
cat("the variance associated to eps sigma2_eps is",sigma2_eps)
sigma2_b <- as.numeric(get_variance_random(fm16.1mer))
cat("the variance associated to random effect sigma2_b is",sigma2_b)

## Let's compute the conditional and marginal var-cov matrix of Y
sgma <- summary(fm16.1mer)$sigma  # sigma^2

A <- getME(fm16.1mer, "A") # A  --> N x n, A represents the D (not italic), variance of random effect
I.n <- Diagonal(ncol(A)) # IN  --> n x n

## the conditional variance-covariance matrix of Y (diagonal matrix)
## conditional to the random effect è semplicemente la matrice fixed effect
cat("\n SigmaErr:\n")
SigmaErr = sgma^2 * (I.n)
# SigmaErr ha dimensione n_oss x n_oss

# Conditioned to the random effects b_i, we observe the var-cov of the errors
# that are independent and homoscedastic

## we visualize the first 20 rows/columns of the matrix
plot(as.matrix(SigmaErr[1:20,1:20]), main = 'Conditional estimated Var-Cov matrix of Y')

cat("the MARGINAL variance-covariance matrix of Y (block-diagonal matrix) is")
V <- sgma^2 * (I.n + crossprod(A)) # V = s^2*(I_N+A*A) --> s^2*(I_N) is the error part, s^2*(A*A) is the random effect part
  #-> V is a block-diagional matrix, the marginal var-cov matrix

# visualization of the first 20 rows/columns
plot(as.matrix(V[1:20,1:20]), main = 'Marginal estimated Var-Cov matrix of Y')


# Another way to interpret the variance output is to note percentage of the subject variance out 
# of the total, i.e. the Percentage of Variance explained by the Random Effect (PVRE).
# This is also called the intraclass correlation (ICC), because it is also an estimate of the within 
# cluster correlation.

PVRE <- sigma2_b/(sigma2_b+sigma2_eps)
cat("The Proportion of Variance due to Random Effect is",PVRE) # 15% is quite high! 

cat("\nvisualization of the random intercepts with their 95% confidence intervals in the dotplot\n")
# Random effects: b_0i for i=1,...,234
dotplot(ranef(fm16.1mer, condVar=T))
```

```{r}
library(plotly)
x = ranef(fm16.1mer, condVar=T)
us_data <- map_data("state")
df <- data.frame(
  state = tolower(rownames(x$state)),
  values = x$state$`(Intercept)`
)
library(usmap)
plot_usmap(data = df) + labs(title = "Cluster by prec")
```

```{r}
# 1) Assessing Assumption on the within-group errors
#it's just a sample from the entire population, so to take with care

plot(fm16.1mer)  ## Pearson and raw residuals are the same now

qqnorm(resid(fm16.1mer))
qqline(resid(fm16.1mer), col='red', lwd=2)
shapiro.test(resid(fm16.1mer))

# 2) Assessing Assumption on the Random Effects

qqnorm(unlist(ranef(fm16.1mer)$state), main='Normal Q-Q Plot - Random Effects on Intercept')
qqline(unlist(ranef(fm16.1mer)$state), col='red', lwd=2)
shapiro.test(unlist(ranef(fm16.1mer)$state))

AIC(fm16.1mer)
```

## LOGIT MIXED MODELS

```{r}
lm_mod_log <- lmer(logit_colony_lost_pct ~ year + months + Varroa.mites +Other.pests.parasites+Disesases+Pesticides+Other+Unknown + (1|state),
                  data = data)
summary(lm_mod_log)
AIC(lm_mod_log)
scale_fill_gradientn(colors = c("#1b98e0", "#f6f805", "#353436"),limits = c(0, 50)) #+ geom_text()
```

```{r}
plot(lm_mod_log)
shapiro.test(residuals(lm_mod_log))
```

```{r}
fm16.1mer <- lm_mod_log
confint(fm16.1mer,oldNames=TRUE)

## Var-Cov matrix of fixed-effects
vcovb <- vcov(fm16.1mer) 
cat("\nVar-Cov matrix of fixed-effects:\n")
vcovb
corb <- cov2cor(vcovb) 
nms <- abbreviate(names(fixef(fm16.1mer)), 5)
rownames(corb) <- nms
cat("\nCorrelation matrix of fixed-effects:\n")
corb

cat("Var-Cov matrix of random-effects and errors\n")
print(vc <- VarCorr(fm16.1mer), comp = c("Variance", "Std.Dev."))

sigma2_eps <- as.numeric(get_variance_residual(fm16.1mer))
cat("the variance associated to eps sigma2_eps is",sigma2_eps)
sigma2_b <- as.numeric(get_variance_random(fm16.1mer))
cat("the variance associated to random effect sigma2_b is",sigma2_b)

## Let's compute the conditional and marginal var-cov matrix of Y
sgma <- summary(fm16.1mer)$sigma  # sigma^2

A <- getME(fm16.1mer, "A") # A  --> N x n, A represents the D (not italic), variance of random effect
I.n <- Diagonal(ncol(A)) # IN  --> n x n

## the conditional variance-covariance matrix of Y (diagonal matrix)
## conditional to the random effect è semplicemente la matrice fixed effect
cat("\n SigmaErr:\n")
SigmaErr = sgma^2 * (I.n)
# SigmaErr ha dimensione n_oss x n_oss

# Conditioned to the random effects b_i, we observe the var-cov of the errors
# that are independent and homoscedastic

## we visualize the first 20 rows/columns of the matrix
plot(as.matrix(SigmaErr[1:20,1:20]), main = 'Conditional estimated Var-Cov matrix of Y')

cat("the MARGINAL variance-covariance matrix of Y (block-diagonal matrix) is")
V <- sgma^2 * (I.n + crossprod(A)) # V = s^2*(I_N+A*A) --> s^2*(I_N) is the error part, s^2*(A*A) is the random effect part
  #-> V is a block-diagional matrix, the marginal var-cov matrix

# visualization of the first 20 rows/columns
plot(as.matrix(V[1:20,1:20]), main = 'Marginal estimated Var-Cov matrix of Y')


# Another way to interpret the variance output is to note percentage of the subject variance out 
# of the total, i.e. the Percentage of Variance explained by the Random Effect (PVRE).
# This is also called the intraclass correlation (ICC), because it is also an estimate of the within 
# cluster correlation.

PVRE <- sigma2_b/(sigma2_b+sigma2_eps)
cat("The Proportion of Variance due to Random Effect is",PVRE) # 15% is quite high! 

cat("\nvisualization of the random intercepts with their 95% confidence intervals in the dotplot\n")
# Random effects: b_0i for i=1,...,234
dotplot(ranef(fm16.1mer, condVar=T))
```

## GAM

```{r}
library(mgcv)
mod_gam = gam(colony_lost_pct ~ year + months + s(Varroa.mites,bs='tp') +Other.pests.parasites+Disesases+Pesticides+Other+Unknown + state, data = data)
summary(mod_gam)
```

```{r}
gam::plot.Gam(mod_gam, se=TRUE)
```
